### ISSUE TITLE
Fine-tuning on ScanQA

### ISSUE THREAD

**Issue by dingjiansw101** [3d-vista/3D-VisTA#18]
Dear Authors,

Thanks for sharing the excellent work. Has the code for fine-tuning on ScanQA been released? And what is the command and config?

Best,
Jian Ding

**Comment by zhuziyu-edward** [comment]
Hi, thank you for your interest in our work. You can run `python3 run.py --config project/vista/scanqa_config.yml`, and change `eval_task=False`  for fine-tuning.

**Comment by dingjiansw101** [comment]
Thanks for your reply. I have successfully finished the training and the evaluation. But I got an error. It seems that the saving failed.

Traceback (most recent call last):
  File "/home/miniconda3/envs/3dvista/lib/python3.8/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/miniconda3/envs/3dvista/lib/python3.8/site-packages/torch/serialization.py", line 591, in _save
    zip_file.write_record('data.pkl', data_value, len(data_value))
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/miniconda3/envs/3dvista/lib/python3.8/site-packages/torch/serialization.py", line 380, in save
    return
  File "/home/miniconda3/envs/3dvista/lib/python3.8/site-packages/torch/serialization.py", line 259, in __exit__
    self.file_like.write_end_of_file()
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 16, in <module>
    pipeline.run_all()
  File "/ibex/user/3D-VisTA/pipeline/pipeline.py", line 29, in run_all
    self.run()
  File "/ibex/user/3D-VisTA/pipeline/pipeline.py", line 151, in run
    self.save_model()
  File "/ibex/user/3D-VisTA/pipeline/pipeline.py", line 348, in save_model
    self.saver.save_dict({'lang_encoder': self.lang_encoder.state_dict(),
  File "/ibex/user/3D-VisTA/utils/saver.py", line 29, in save_dict
    torch.save(state_dict, self.save_path)
  File "/home/miniconda3/envs/3dvista/lib/python3.8/site-packages/torch/serialization.py", line 381, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/home/miniconda3/envs/3dvista/lib/python3.8/site-packages/torch/serialization.py", line 225, in __exit__
    self.file_like.flush()
AttributeError: 'NoneType' object has no attribute 'flush'

**Comment by cy94** [comment]
Hi @zhuziyu-edward, zhuziyu-edward could you point me to the file `scannetv2_raw_categories.json` that is required for ScanQA finetuning?

**Comment by cy94** [comment]
Hi @dingjiansw101 could you tell me how you did the ScanQA finetuning? I couldn't find these files - `scannetv2_raw_categories.json` and `cat2glove42b.json`.
